# Generated by Django 3.2.6 on 2021-08-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20210828_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_recieved',
        ),
    ]
